#### Ansible inventory.
resource "local_file" "ansible_inventory" {
  depends_on = [ module.vsi ]
  content = <<-DOC
all:
  hosts:
    db_host:
      ansible_host: "${data.ibm_is_instance.vsi.primary_network_interface[0].primary_ip[0].address}"
    DOC
  filename = "ansible/inventory.yml"
}

# Export Terraform variable values to an Ansible var_file
resource "local_file" "ansible_saphana-vars" {
  content = <<-DOC
---
# Ansible vars_file containing variable values passed from Terraform.
# Generated by "terraform plan&apply" command.
hana_profile: "${var.PROFILE}"
#HANA DB configuration
hana_sid: "${var.HANA_SID}"
hana_sysno: "${var.HANA_SYSNO}"
hana_main_password: "${var.HANA_MAIN_PASSWORD}"
hana_system_usage: "${var.HANA_SYSTEM_USAGE}"
hana_components: "${var.HANA_COMPONENTS}"

# Kits paths
kit_saphana_file: "${var.KIT_SAPHANA_FILE}"
...
    DOC
  filename = "ansible/saphana-vars.yml"
}

# Export Terraform variable values to an Ansible var_file
resource "local_file" "tf_ansible_vars_generated_file" {
  depends_on = [ module.vsi ]
  source = "files/hana_volume_layout.json"
  filename = "ansible/hana_volume_layout.json"
}

