# Export Terraform variable values to an Ansible var_file
resource "local_file" "ansible_saphana-vars" {
  content = <<-DOC
---
# Ansible vars_file containing variable values passed from Terraform.
# Generated by "terraform plan&apply" command.
hana_profile: "${var.PROFILE}"
#HANA DB configuration
hana_sid: "${var.hana_sid}"
hana_sysno: "${var.hana_sysno}"
hana_main_password: "${var.hana_main_password}"
hana_system_usage: "${var.hana_system_usage}"
hana_components: "${var.hana_components}"

# Kits paths
kit_saphana_file: "${var.kit_saphana_file}"
...
    DOC
  filename = "ansible/saphana-vars.yml"
}

# Export Terraform variable values to an Ansible var_file
resource "local_file" "tf_ansible_hana_storage_generated_file" {
  depends_on = [ module.vsi ]
  source = "files/hana_volume_layout.json"
  filename = "ansible/hana_volume_layout.json"
}